baseURL = 'https://03chrissy.github.io/chrissy/'
languageCode = 'en-us'
title = '兰州刻葫芦'
theme = 'ananke'
publishDir =  "docs"
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
canonifyurls = true