baseURL = 'https://03chrissy.github.io/chrissy/'
languageCode = 'en-us'
title = '巴以冲突系列报道'
theme = 'ananke'
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
publishDir =  "docs"
